# Site settings
title: Arianna Yuan
email: xfyuan@stanford.edu
copyright_name: ariannayuan
github_username: ariannayuan

collections:
  vehicles :
  teams:
  subteam :
  competition :
  research :
  people:

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
