# Site settings
title: Arianna Yuan
email: arianna.yuan1@gmail.com
copyright_name: ariannayuan
github_username: ariannayuan

collections:
  vehicles :
  teams:
  subteam :
  competition_wide :
  competition :
  research :
  people:

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]


